package main

import "fmt"

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

func fibEvenSum(x int) int {

	if x == 0 {
		return 0
	}

	if x == 1 {
		return 1
	}

	fibNumbers := []int{1, 2}
	sum := 2
	for i := 0; sum <= x; i++ {
		fmt.Println("fib number: ", fibNumbers[i]+fibNumbers[i+1])

		next := fibNumbers[i] + fibNumbers[i+1]
		fibNumbers = append(fibNumbers, next)
		if next%2 == 0 {
			sum += next
		}
	}
	return sum
}

func main() {
	fmt.Println(fibEvenSum(8))
}
